name: Upload Test Results

on: [workflow_dispatch]

permissions:
  checks: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Upload JUnit results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: Test_Report_github_standard.xml
        check_name: Test Results
        comment_title: Test Report
        job_summary: true
